resources:
  repositories:
    - repository: templatesRepo
      type: git
      name: PipelineSamplesTemplates/templates-apim
      ref: refs/heads/main
    
    - repository: templatesInfra
      type: git
      name: PipelineSamplesTemplates/infra
      ref: refs/heads/main

trigger: none

parameters:
  - name: BuildTool
    type: string
    default: 'Gradle'
    values:
      - 'Gradle'
      - 'Maven'

variables:
  imageName: 'koniasample'

stages:
  - stage: Build
    displayName: "Build Java App"
    jobs:
      - ${{ if eq(parameters.BuildTool, 'Gradle') }}:
        - template: build-gradle-template.yml@templatesRepo
          parameters:
            buildConfiguration: 'Release'
      - ${{ if eq(parameters.BuildTool, 'Maven') }}:
        - template: build-maven-template.yml@templatesRepo
          parameters:
            buildConfiguration: 'Release'

  - stage: Docker
    displayName: "Build Docker Image and Push to ACR"
    dependsOn: Build
    jobs:
      - template: docker-build-template.yml@templatesRepo
        parameters:
          registryName: 'acrkoniasamples.azurecr.io'
          imageName: $(imageName)
          tag: $(Build.BuildId)
          artifactName: 'drop'

  - stage: DeployDev
    displayName: "Deploy to DEV"
    dependsOn: Docker
    jobs:
      - template: deploy-aca-template.yml@templatesRepo
        parameters:
          environmentName: 'DEV'
          imageTag: $(Build.BuildId)
          imageName: $(imageName)

      - template: development/deploy-apim-template.yml@templatesInfra
        parameters:
          environmentName: 'DEV'
          apiName: 'koniasample-api'
          apiPath: 'koniasample'
          apiSpecFile: 'openapi/dev-koniasample.json'
          apimInstance: 'apim-koniasamples'

  - stage: DeployQA
    displayName: "Deploy to QA"
    dependsOn: DeployDev
    jobs:
      - template: deploy-aca-template.yml@templatesRepo
        parameters:
          environmentName: 'QA'
          imageTag: $(Build.BuildId)
          imageName: $(imageName)

      - template: development/deploy-apim-template.yml@templatesInfra
        parameters:
          environmentName: 'QA'
          apiName: 'koniasample-api'
          apiPath: 'koniasample'
          apiSpecFile: 'openapi/dev-koniasample.json'
          apimInstance: 'apim-koniasamples-qa'

  - stage: DeployHML
    displayName: "Deploy to HML"
    dependsOn: DeployQA
    jobs:
      - template: deploy-aca-template.yml@templatesRepo
        parameters:
          environmentName: 'HML'
          imageTag: $(Build.BuildId)
          imageName: $(imageName)

      - template: development/deploy-apim-template.yml@templatesInfra
        parameters:
          environmentName: 'HML'
          apiName: 'koniasample-api'
          apiPath: 'koniasample'
          apiSpecFile: 'openapi/dev-koniasample.json'
          apimInstance: 'apim-koniasamples-hml'

  - stage: DeployProd
    displayName: "Deploy to PROD"
    dependsOn: DeployHML
    jobs:
      - template: deploy-aca-template.yml@templatesRepo
        parameters:
          environmentName: 'PRD'
          imageTag: $(Build.BuildId)
          imageName: $(imageName)

      - template: development/deploy-apim-template.yml@templatesInfra
        parameters:
          environmentName: 'PRD'
          apiName: 'koniasample-api'
          apiPath: 'koniasample'
          apiSpecFile: 'openapi/dev-koniasample.json'
          apimInstance: 'apim-koniasamples-prd'
