resources:
  repositories:
    - repository: templatesRepo
      type: git
      name: PipelineSamplesTemplates/templates-apim
      ref: refs/heads/main
    
    - repository: templatesInfra
      type: git
      name: PipelineSamplesTemplates/infra
      ref: refs/heads/main

trigger: none

parameters:
  - name: Agente
    type: string
    default: 'ubuntu-latest'
    values:
      - 'ubuntu-latest'
      - 'ubuntu-22.04'
      - 'ubuntu-24.04'
      - 'Konia-Pool'
  - name: ApplicationName
    type: string
    default: '$(Build.Repository.Name)'
  - name: ArtifactName
    type: string
    default: 'drop'
  - name: BuildTool
    type: string
    default: 'Gradle'
    values:
      - 'Gradle'
      - 'Maven'

variables:
  imageName: 'koniasample'
  System.TeamProject: '$(System.TeamProject)' # Nome do projeto onde esta a pipeline
  ContentPath: '$(System.DefaultWorkingDirectory)' # Caminho para os arquivos que serão copiados para a pasta do pacote que será gerado.
  SonarConnection: '' # Nome da Service Connection do Sonaqube
  SonarProjectKey: '' # ProjectKey do projeto no Sonarqube
  SonarProjectName: '' # ProjectName do projeto no Sonarqube

stages:
  - stage: Build
    displayName: "Build Java App"
    jobs:
      - ${{ if eq(parameters.BuildTool, 'Gradle') }}:
        - template: build-gradle-template.yml@templatesRepo
          parameters:
            Agente: ${{ parameters.Agente }}
            ApplicationName: ${{ parameters.ApplicationName }}
            ArtifactName: ${{ parameters.ArtifactName }}
      - ${{ if eq(parameters.BuildTool, 'Maven') }}:
        - template: build-maven-template.yml@templatesRepo
          parameters:
            Agente: ${{ parameters.Agente }}
            ApplicationName: ${{ parameters.ApplicationName }}
            ArtifactName: ${{ parameters.ArtifactName }}

  - stage: Docker
    displayName: "Build Docker Image and Push to ACR"
    dependsOn: Build
    jobs:
      - template: docker-build-template.yml@templatesRepo
        parameters:
          registryName: 'acrkoniasamples.azurecr.io'
          imageName: $(imageName)
          tag: $(Build.BuildId)
          artifactName: 'drop'

  - stage: DeployDev
    displayName: "Deploy to DEV"
    dependsOn: Docker
    jobs:
      - template: deploy-aca-template.yml@templatesRepo
        parameters:
          environmentName: 'DEV'
          imageTag: $(Build.BuildId)
          imageName: $(imageName)

      

  - stage: DeployQA
    displayName: "Deploy to QA"
    dependsOn: DeployDev
    jobs:
      - template: deploy-aca-template.yml@templatesRepo
        parameters:
          environmentName: 'QA'
          imageTag: $(Build.BuildId)
          imageName: $(imageName)

     

  - stage: DeployHML
    displayName: "Deploy to HML"
    dependsOn: DeployQA
    jobs:
      - template: deploy-aca-template.yml@templatesRepo
        parameters:
          environmentName: 'HML'
          imageTag: $(Build.BuildId)
          imageName: $(imageName)

      

  - stage: DeployProd
    displayName: "Deploy to PROD"
    dependsOn: DeployHML
    jobs:
      - template: deploy-aca-template.yml@templatesRepo
        parameters:
          environmentName: 'PRD'
          imageTag: $(Build.BuildId)
          imageName: $(imageName)

      
