resources:
  repositories:
    - repository: templatesRepo
      type: git
      name: PipelineSamplesTemplates/templates-apim
      ref: refs/heads/main
    
trigger: none

parameters:
  - name: pool
    type: string
    default: 'ubuntu-latest'
    values:
      - 'ubuntu-latest'
      - 'ubuntu-24.04'
      - 'Konia-Pool'
  - name: ApplicationName
    type: string
    default: '$(Build.Repository.Name)'
  - name: ApiGroup
    type: string
    default: 'appcontainer'
  - name: ArtifactName
    type: string
    default: 'drop'
  - name: BuildTool
    type: string
    default: 'Gradle'
    values:
      - 'Gradle'
      - 'Maven'

variables:
  baseImageName: '${{ parameters.ApiGroup }}-${{ parameters.ApplicationName }}'
  ContentPath: '$(System.DefaultWorkingDirectory)' 
  SonarConnection: '' 
  SonarProjectKey: '' 
  SonarProjectName: '' 

stages:
  - stage: Build
    displayName: "Build Java App"
    jobs:
      - ${{ if eq(parameters.BuildTool, 'Gradle') }}:
        - template: build-gradle-template.yml@templatesRepo
          parameters:
            pool: ${{ parameters.pool }}
            ApplicationName: ${{ parameters.ApplicationName }}
            ArtifactName: ${{ parameters.ArtifactName }}
      - ${{ if eq(parameters.BuildTool, 'Maven') }}:
        - template: development/api/java/build-maven-template.yml@templatesRepo
          parameters:
            pool: ${{ parameters.pool }}
            ApplicationName: ${{ parameters.ApplicationName }}
            ArtifactName: ${{ parameters.ArtifactName }}

  # -----------------------------
  # Deploy DEV
  # -----------------------------
  - stage: DeployDev
    displayName: "Deploy to DEV"
    dependsOn: Build
    jobs:
      - template: docker-build-template.yml@templatesRepo
        parameters:
          registryName: 'acrkoniasamples.azurecr.io'
          imageName: "$(baseImageName)-dev"
          tag: $(Build.BuildId)
          artifactName: 'drop'
          ApplicationName: '${{ parameters.ApplicationName }}'

      - template: deploy-aca-template.yml@templatesRepo
        parameters:
          environmentName: 'DEV'
          imageTag: $(Build.BuildId)
          imageName: "$(baseImageName)-dev"
          ApiGroup: '${{ parameters.ApiGroup }}'
          ApplicationName: '${{ parameters.ApplicationName }}'

  # -----------------------------
  # Deploy QA
  # -----------------------------
  - stage: DeployQA
    displayName: "Deploy to QA"
    dependsOn: DeployDev
    jobs:
      - template: docker-build-template.yml@templatesRepo
        parameters:
          registryName: 'acrkoniasamples.azurecr.io'
          imageName: "$(baseImageName)-qa"
          tag: $(Build.BuildId)
          artifactName: 'drop'

      - template: deploy-aca-template.yml@templatesRepo
        parameters:
          environmentName: 'QA'
          imageTag: $(Build.BuildId)
          imageName: "$(baseImageName)-qa"
          ApiGroup: '${{ parameters.ApiGroup }}'

  # -----------------------------
  # Deploy HML
  # -----------------------------
  - stage: DeployHML
    displayName: "Deploy to HML"
    dependsOn: DeployQA
    jobs:
      - template: docker-build-template.yml@templatesRepo
        parameters:
          registryName: 'acrkoniasamples.azurecr.io'
          imageName: "$(baseImageName)-hml"
          tag: $(Build.BuildId)
          artifactName: 'drop'

      - template: deploy-aca-template.yml@templatesRepo
        parameters:
          environmentName: 'HML'
          imageTag: $(Build.BuildId)
          imageName: "$(baseImageName)-hml"
          ApiGroup: '${{ parameters.ApiGroup }}'

  # -----------------------------
  # Deploy PROD
  # -----------------------------
  - stage: DeployProd
    displayName: "Deploy to PROD"
    dependsOn: DeployHML
    jobs:
      - template: docker-build-template.yml@templatesRepo
        parameters:
          registryName: 'acrkoniasamples.azurecr.io'
          imageName: "$(baseImageName)-prd"
          tag: $(Build.BuildId)
          artifactName: 'drop'

      - template: deploy-aca-template.yml@templatesRepo
        parameters:
          environmentName: 'PRD'
          imageTag: $(Build.BuildId)
          imageName: "$(baseImageName)-prd"
          ApiGroup: '${{ parameters.ApiGroup }}'
